# top level stuff you probably don't need to touch
highlighter: rouge
kramdown:
  input: GFM
markdown: kramdown
extensions: [smart]
permalink: /:title.html
_yaml_mode: loose
_content_type: markdown
_markdown_parser: parsedown
#paginate: 5
port: 5000
safe: true



# edit here to achieve your personal greatness
url: "https://carrahlingo.com"
baseurl: ""
title: Carrah Lingo
author: Carrah Lingo
description: Personal site
avatar: carrah.png
email: "carrahlingo@gmail.com"
github: "carrahlingo"
twitter: ""
google_analytics: ""
